use_frameworks!

platform :ios, '9.0'

target 'kGradientColor_Example' do
  pod 'kGradientColor', :path => '../'

  target 'kGradientColor_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
